<a href="https://colab.research.google.com/github/dayobola/CMM536/blob/master/Adedayo_CMM560_Coursework_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this version, you will "mount" your Google Drive in the Colab Notebook and you will use the files there


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Version 1: Converting your image repository into numpy arrays

In [2]:
import os
import numpy as np
import cv2
resize_width = 100
resize_height = 100
path = '/content/drive/MyDrive/data' # CHANGE FOR YOURS!!
resized_images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target
flattened_images = [] # list to append the flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height))
                # Append the resized image to a list
                resized_images.append(img)
                # Append the flattened image to a list
                flattened_images.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the list into numpy array
flattened_images = np.array(flattened_images)
print(flattened_images)
print(flattened_images.shape)
print(target)
print(len(target))

Invalid file .DS_Store skipped.
Invalid file .DS_Store skipped.
Invalid file rusted_airplane_53.jpg skipped.
Invalid file rusted_objects_40.jpg skipped.
[[255 255 255 ... 179 181 172]
 [ 63  64  67 ... 141 160 145]
 [180 128  34 ... 100 150 131]
 ...
 [225 186 212 ...  89  71  71]
 [ 42  45  47 ...  24  27  25]
 [ 76  71  76 ...   9  11   7]]
(584, 10000)
['SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositive', 'SurfacePositi

# Version 2: Converting your image repository into Pandas data frames

In [3]:
import os
import numpy as np
import cv2
from pandas import DataFrame

resize_width = 25
resize_height = 25
path = '/content/drive/MyDrive/data' # CHANGE FOR YOURS!!
resized_images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target

cont = 0
for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height))
                # Append the resized image to a list
                resized_images.append(img)
                # Append the flattened image to the list
                if cont == 0:
                    flattened_images = img.flatten().copy()
                    cont+=1
                else:
                    flattened_images = np.vstack((flattened_images,img.flatten()))
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the list into a pandas dataframe
flattened_images_withtarget = DataFrame(flattened_images)
flattened_images_withtarget = abs(flattened_images_withtarget)
flattened_images_withtarget['class']=DataFrame(target)
flattened_images_withtarget

Invalid file .DS_Store skipped.
Invalid file .DS_Store skipped.
Invalid file rusted_airplane_53.jpg skipped.
Invalid file rusted_objects_40.jpg skipped.


0    1    2    3    4    5    6    7    8    9  ...  616  617  618  \
0    255  255  255  255  253  245  221  229  228  221  ...  108  171  147   
1     67   67   71   81   82   94   86   92   95   94  ...    5   30   34   
2     32  174  171  174   96  135  174  183  167  131  ...  123  151   67   
3    191  192  194  195  197  197  198  199  201  202  ...  117  149  148   
4    184  190  162  195  201  198  201  202  205  205  ...  201  200  196   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
765  152  162  112  146  154   51   32   34   32   33  ...   25   37   21   
766    6    5   46   51   52   49   39   43   36   41  ...   20   20   26   
767  168  137  138  121  173   87   89  161  198  164  ...  160  178  202   
768   44   47   42   46   51   54   50   54   58   63  ...    4    4    3   
769   69   69   68   69   75   75   80   81   83   85  ...   21    7   46   

     619  620  621  622  623  624               class  
0    159  126  150  164  175  140     SurfacePositive  
1    159  183  159  170  118  142     SurfacePositive  
2    124  166  122  168   78  130     SurfacePositive  
3    148  149  148  147  147  147     SurfacePositive  
4    195  192  191  185  193  187     SurfacePositive  
..   ...  ...  ...  ...  ...  ...                 ...  
765   45   70   77  104  102  112  UnderwaterNegative  
766   24   27   20    2    2    1  UnderwaterNegative  
767  132  194  200  182  170   76  UnderwaterNegative  
768    5    7    6   11   28   26  UnderwaterNegative  
769   23   14   45   10    8   11  UnderwaterNegative  

[770 rows x 626 columns]

The values in the data structures are different because in the `numpy array` the images are resized to $100 \times 100$ while the `pandas dataframe` contains $25 \times 25$ flattened images plus the **class/label/target** in the last column.